version: "3"
services:
  issue-tracker:
    build: src
    image: issue-tracker:latest
    ports:
      - "8080:8080"
    networks:
      - issue-2-db
    depends_on:
      - mysql-db
    container_name: issue-tracker

  mysql-db:
    image: mysql
    networks:
      - issue-2-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=issue-tracker
    container_name: mysql-db

networks:
  issue-2-db:

